### ISSUE TITLE
Timer going increasingly negative when logged in without gear

### ISSUE THREAD

**Issue by YvesW** [ngraves95/attacktimer#10]
![image](https://user-images.githubusercontent.com/7929021/216840733-9c02042b-99dc-4532-aec6-300a7d1bc1f0.png)

I just freshly logged in without anything on and an empty inventory. IIRC the ItemContainer can be null at that point, so that'd explain the problem.

NPE:
``2023-02-05 20:28:41 [Client] WARN  n.runelite.client.eventbus.EventBus - Uncaught exception in event subscriber
java.lang.NullPointerException: Cannot invoke "net.runelite.api.ItemContainer.getItem(int)" because "container" is null
	at com.attacktimer.AttackTimerMetronomePlugin.getItemStatsFromContainer(AttackTimerMetronomePlugin.java:80)
	at com.attacktimer.AttackTimerMetronomePlugin.getWeaponStats(AttackTimerMetronomePlugin.java:85)
	at com.attacktimer.AttackTimerMetronomePlugin.getWeaponSpeed(AttackTimerMetronomePlugin.java:104)
	at com.attacktimer.AttackTimerMetronomePlugin.performAttack(AttackTimerMetronomePlugin.java:128)
	at com.attacktimer.AttackTimerMetronomePlugin.onGameTick(AttackTimerMetronomePlugin.java:205)
	at net.runelite.client.eventbus.EventBus$Subscriber.invoke(EventBus.java:70)
	at net.runelite.client.eventbus.EventBus.post(EventBus.java:223)
	at net.runelite.client.callback.Hooks.tick(Hooks.java:207)
	at client.ac(client.java:31956)
	at client.an(client.java)
	at an.ao(an.java:390)
	at an.run(an.java:369)
	at java.base/java.lang.Thread.run(Thread.java:833)``

And the following ArrayIndexOutOfBoundsException but that was probably when I equipped a whip again.
``2023-02-05 20:31:38 [Client] WARN  n.r.c.ui.overlay.OverlayRenderer - Error during overlay rendering
java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 0
	at com.watsoncluetracker.WatsonOverlay.render(WatsonOverlay.java:40)
	at net.runelite.client.ui.overlay.OverlayRenderer.safeRender(OverlayRenderer.java:735)
	at net.runelite.client.ui.overlay.OverlayRenderer.renderOverlays(OverlayRenderer.java:328)
	at net.runelite.client.ui.overlay.OverlayRenderer.renderOverlayLayer(OverlayRenderer.java:235)
	at net.runelite.client.callback.Hooks.drawAboveOverheads(Hooks.java:496)
	at ht.uc(ht.java:51287)
	at ht.fy(ht.java:116)
	at bj.hb(bj.java:4730)
	at ay.kv(ay.java:10421)
	at ay.kv(ay.java:10452)
	at ay.kv(ay.java:10452)
	at ay.kv(ay.java:10452)
	at ce.ke(ce.java:10310)
	at client.hq(client.java:4330)
	at client.ab(client.java:1126)
	at an.am(an.java:416)
	at an.run(an.java:370)
	at java.base/java.lang.Thread.run(Thread.java:833)``

**Comment by GuilhermeZanin** [comment]
I also noticed this issue if you unequip weapons as well to unarmed, it bugs out the plugin, visual metronome and Monster HP Percentage Plugin.

**Comment by YvesW** [comment]
@ngraves95 Any reason you closed this issue? I can still repro it. In this example I banked my equipment + invent, closed the client and reopened it. First attack I did.

https://github.com/ngraves95/attacktimer/assets/7929021/3c72d055-83ca-42e0-8081-ba318aa26b82
