### ISSUE TITLE
NullPointer Exception in overlay AttackTimerMetronomeTileOverlay.java:67

### ISSUE THREAD

**Issue by pwatts6060** [ngraves95/attacktimer#25]
2023-10-27 17:39:05 GST [Client] WARN  n.r.c.ui.overlay.OverlayRenderer - Error during overlay rendering
java.lang.NullPointerException: null
	at net.runelite.client.ui.overlay.OverlayUtil.renderTextLocation(OverlayUtil.java:97)
	at com.attacktimer.AttackTimerMetronomeTileOverlay.render(AttackTimerMetronomeTileOverlay.java:67)
	at net.runelite.client.ui.overlay.OverlayRenderer.safeRender(OverlayRenderer.java:734)
	at net.runelite.client.ui.overlay.OverlayRenderer.renderOverlays(OverlayRenderer.java:328)
	at net.runelite.client.ui.overlay.OverlayRenderer.renderOverlayLayer(OverlayRenderer.java:235)
	at net.runelite.client.callback.Hooks.drawAboveOverheads(Hooks.java:502)
	at jq.yn(jq.java:59765)
	at jq.lc(jq.java:122)
	at qy.jw(qy.java:5090)
	at jh.lb(jh.java:10739)
	at jh.lb(jh.java:10770)
	at pb.lz(pb.java:10634)
	at client.id(client.java:4675)
	at client.bp(client.java:1130)
	at bb.bd(bb.java:388)
	at bb.run(bb.java:337)
	at java.base/java.lang.Thread.run(Unknown Source)

**Comment by ngraves95** [comment]
Can you share repro steps?
